export default {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
  RESET: "RESET",
  SET_USER_INFO: "SET_USER_INFO",
  SET_USER_Image: "SET_USER_Image",
  TODAY_MEETING: 'TODAY_MEETING',
  NEXT_MEETING: 'NEXT_MEETING'
};
